name: Release production
on:
  push:
    branches:
      - production
jobs:
  release:
    name: Release stuff
    runs-on: ubuntu-latest
    steps:
      - name: Current branch names
        run: |
          echo getting env secrets
          echo ${{secrets.TEST}}
